name: Build and Test

on:
  push:
    branches:
        - master
        - 'feature/*'
  pull_request:
    branches: 
        - master
        - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the pytrade image
      run: docker build . --file Dockerfile -t pytrade
    - name: Test the build
      run: docker run --env BINANCE_API_KEY=${{secrets.BINANCE_API_KEY}} --env BINANCE_API_SECRET=${{secrets.BINANCE_API_SECRET}} -t pytrade ./test.py